### ISSUE TITLE
worker1 frequently times out

### ISSUE THREAD

**Issue by dnuttle** [tdi/vagrant-docker-swarm#6]
I don't think this is really an issue with the project, but after starting a 3-node swarm and creating a service using darek/goweb, I found that worker1 times out frequently. Sometimes it will send back a valid HTTP response; usually it times out after 30 seconds. manager and worker2 both seem to work just fine. And I can see that all three nodes are being hit, based on the IDs after "hi from". Any thoughts on what might be happening? By the way the same thing happens if I start the service with only one replica, regardless of which node the replica is on. And it still happens after doing a vagrant halt and up, and re-recreating the service.

Is the code for darek/goweb available? I didn't find it on github.

**Comment by tdi** [comment]
The code for goweb is very simple, here it is. 

`package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
)

func handler(w http.ResponseWriter, r *http.Request) {
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "hostname"
	}
	fmt.Fprintf(w, "hi from %s ! version 2.0\n", hostname)
	for h, v := range r.Header {
		fmt.Fprintf(w, "%v:%v\n", h, v)
	}
	log.Printf("Connection from %v", r.RemoteAddr)
}

func main() {
	log.Println("Starting goweb 2.0")
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8080", nil)
}`

**Comment by dnuttle** [comment]
Thank you so much. And by the way, later on, the timeouts went away for reasons unknown, and all three nodes responded quickly.
